### ISSUE TITLE
Error setting directory

### ISSUE THREAD

**Issue by pulimento** [vigneshuvi/SwiftLoggly#1]
If I set the directory this way:

````
let documentsDirectory = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
let logsDirectory = URL(fileURLWithPath: documentsDirectory).appendingPathComponent("logs", isDirectory: true)
Loggly.logger.directory = logsDirectory.path
`````
Logger fails silently, and stops working. Perhaps it must throw an error (or a info message), or accept a URL instead of a String

**Comment by vignesh-kumar-p** [comment]
Can you please give some examples to reproduce your issue?
Let me know you swift version!

**Comment by vigneshuvi** [comment]
Give me sometime, I will take a look into this issue.

**Comment by vigneshuvi** [comment]
@pulimento , I have investigated this issue and release new version. Please let me know if you face this issue again!

-> [SwiftLoggly (1.0.6)](https://github.com/vigneshuvi/SwiftLoggly/releases/tag/1.0.6)

**Comment by pulimento** [comment]
Still failing, because is not creating the new folder and/or file. I've just created a pull request for that, please review it.
