### ISSUE TITLE
Can't use emojis

### ISSUE THREAD

**Issue by pulimento** [vigneshuvi/SwiftLoggly#2]
isEmojis is always false. Is this intended?

As far I see, lib decides to use emojis or not based on 'logTypeName' function. This function is only called from [here](https://github.com/vigneshuvi/SwiftLoggly/blob/master/Sources/Loggly.swift#L560)

Thanks in advance

**Comment by vigneshuvi** [comment]
Please try with following version and let me know. You issue is fixed or not. I will make it available in cocoa-pods once getting you confirmation. 

```
// Enable/Disable Emojis
Loggly.logger.enableEmojis = false
```

`pod 'SwiftLoggly', :git => 'https://github.com/vigneshuvi/SwiftLoggly.git', :tag => '1.0.3'`

**Comment by pulimento** [comment]
OK, i'll try it! Thanks

**Comment by vigneshuvi** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SwiftLoggly (1.0.6) successfully published
 📅  January 22nd, 18:09
 🌎  https://cocoapods.org/pods/SwiftLoggly
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by pulimento** [comment]
Tried it, and working fine. Thanks
