### ISSUE TITLE
Feature proposal: Capture STDOUT / STDERR

### ISSUE THREAD

**Issue by pulimento** [vigneshuvi/SwiftLoggly#6]
Would be useful to capture log produced by third party code (e.g. cocoapods dependencies). Those lines are shown in the XCode console, but don't go through SwiftLoggly.

**Comment by vigneshuvi** [comment]
@pulimento , It is all based on your need to capture log details.

Take a example, Like if you are calling web service use Alamofire.framework. It will return some error response when web service is failed, It's your wish to track them or not! 

Where you are going to Capture log?

**Comment by pulimento** [comment]
@vigneshuvi don't worry too much, it's only a proposal.

Alamofire has callbacks, so errors goes through my own code. I mean, for example, crashlytics debug log. Or the lib I use to communicate with SAP systems. There are plenty of examples.

**Comment by vigneshuvi** [comment]
Ok thanks for your proposal. It's not usual to track those third party logs! However, i will take this proposal and will work it on later. :)
